# Generated by Django 4.2.30 on 2026-06-17 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendrierEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='FAQEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('reponse', models.TextField()),
                ('categorie', models.CharField(choices=[('admission', 'Admission & Inscription'), ('bourse', 'Bourses & Frais'), ('logement', 'Logement & Vie'), ('autre', 'Autre')], default='autre', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Universite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('sigle', models.CharField(max_length=20, unique=True)),
                ('ville', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('capacite', models.IntegerField(default=0)),
                ('color', models.CharField(default='#1a56db', max_length=20)),
                ('image_url', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MessageFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_positif', models.BooleanField()),
                ('commentaire', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='chatbot.message')),
            ],
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('moyenne_requise', models.FloatField(default=10.0)),
                ('profils_acceptes', models.CharField(help_text='ex: SE, SM, SS-FA', max_length=100)),
                ('capacite', models.IntegerField(default=0)),
                ('duree', models.CharField(default='3 ans', max_length=50)),
                ('debouches', models.TextField(blank=True)),
                ('conditions_admission', models.TextField(blank=True)),
                ('universite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filieres', to='chatbot.universite')),
            ],
        ),
    ]
